package com.girl.code.hackathon.kopano.activities;

import android.content.DialogInterface;
import android.content.Intent;
import android.os.Bundle;
import android.view.Menu;
import android.view.MenuInflater;
import android.view.MenuItem;
import android.view.View;

import androidx.annotation.NonNull;
import androidx.appcompat.app.AlertDialog;
import androidx.appcompat.app.AppCompatActivity;
import androidx.appcompat.widget.Toolbar;
import androidx.core.view.GravityCompat;
import androidx.drawerlayout.widget.DrawerLayout;
import androidx.navigation.NavController;
import androidx.navigation.Navigation;
import androidx.navigation.ui.AppBarConfiguration;
import androidx.navigation.ui.NavigationUI;

import com.girl.code.hackathon.kopano.R;
import com.girl.code.hackathon.kopano.utils.AppPrefManager;
import com.google.android.material.floatingactionbutton.FloatingActionButton;
import com.google.android.material.navigation.NavigationView;
import com.google.android.material.snackbar.Snackbar;

public class CitizenHomeActivity extends AppCompatActivity {

    private AppBarConfiguration mAppBarConfiguration;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_citizen_home);

        /*Auto generated by android studio, when creating android project*/
        Toolbar toolbar = findViewById(R.id.toolbar_citizen);
        setSupportActionBar(toolbar);
        /**/

        //create reference to the floating action button
        FloatingActionButton fab = findViewById(R.id.fab_citizen);
        //set on click listener to the fab button
        fab.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                //show snack bar after clicking the fab button
                Snackbar.make(view, "Do you want to make a request?", Snackbar.LENGTH_LONG)
                        .setAction("Yes", new View.OnClickListener() {
                            @Override
                            public void onClick(View view) {//user clicked the yes button
                                //open make request activity
                                startActivity(new Intent(view.getContext(), MakeRequest.class));
                            }
                        }).show();
            }
        });

        /*Auto generated by android studio, when creating android project*/
        final DrawerLayout drawer = findViewById(R.id.citizen_drawer_layout);
        NavigationView navigationView = findViewById(R.id.nav_view_citizen);
        // Passing each menu ID as a set of Ids because each
        // menu should be considered as top level destinations.
        mAppBarConfiguration = new AppBarConfiguration.Builder(
                R.id.nav_news_letter, R.id.nav_my_request, R.id.nav_citizen_accepted_request)/*mod*/
                .setDrawerLayout(drawer)
                .build();
        NavController navController = Navigation.findNavController(this, R.id.nav_host_fragment_citizen);/*mod*/
        NavigationUI.setupActionBarWithNavController(this, navController, mAppBarConfiguration);
        NavigationUI.setupWithNavController(navigationView, navController);
        /**/
    }

    //adds a menu button to the top right corner
    @Override
    public boolean onCreateOptionsMenu(Menu menu)
    {
        MenuInflater inflater = getMenuInflater();
        inflater.inflate(R.menu.menu, menu);
        return true;
    }

    //this function handles click events on a menu item
    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        // Handle item selection
        if (item.getItemId() == R.id.log_out) { //if the user clicked log out
            logOut();
            return true;
        }
        return super.onOptionsItemSelected(item);
    }

    //this function creates and shows an alert dialog
    //which asks the user if they want to log out
    private void logOut() {

        new AlertDialog.Builder(CitizenHomeActivity.this)
                .setTitle("Log Out")
                .setIcon(R.mipmap.ic_launcher)
                .setMessage("Are you sure you want to log out?")
                .setPositiveButton("Yes", new DialogInterface.OnClickListener() {
                    @Override
                    public void onClick(DialogInterface dialogInterface, int i) {
                        //if user is logging out, we create an instance of
                        //the appPreferences and clear all the values
                        //the values cleared are the users id
                        new AppPrefManager(CitizenHomeActivity.this).clearAllValues();
                        //then goes to the login page
                        startActivity(new Intent(CitizenHomeActivity.this, LogInActivity.class));
                        //and closes the current activity
                        finish();
                    }
                })
                .setNegativeButton("No", new DialogInterface.OnClickListener() {
                    @Override
                    public void onClick(DialogInterface dialogInterface, int i) {
                        //close the alertDialog
                        dialogInterface.dismiss();
                    }
                }).create().show();
    }

    /**Auto generated by android studio, when creating android project*/
    @Override
    public boolean onSupportNavigateUp() {
        NavController navController = Navigation.findNavController(this, R.id.nav_host_fragment_citizen);
        return NavigationUI.navigateUp(navController, mAppBarConfiguration)
                || super.onSupportNavigateUp();
    }
    /**/
}
